/**
 * @author Raido Pahtma
 * @license MIT
 **/
#ifndef BOOTSLIFETIME_H_
#define BOOTSLIFETIME_H_

#ifndef BOOTSLIFETIME_STORAGE_PERIOD_S
#define BOOTSLIFETIME_STORAGE_PERIOD_S 300
#endif // BOOTSLIFETIME_STORAGE_PERIOD_S

#ifndef BOOTSLIFETIME_STABILIZATION_PERIOD_S
#define BOOTSLIFETIME_STABILIZATION_PERIOD_S 60
#endif // BOOTSLIFETIME_STABILIZATION_PERIOD_S

#ifndef BOOTSLIFETIME_RETRY_PERIOD_MS
#define BOOTSLIFETIME_RETRY_PERIOD_MS 500
#endif // BOOTSLIFETIME_RETRY_PERIOD_MS

#ifndef BOOTSLIFETIME_ACTION_DELAY_MS
#define BOOTSLIFETIME_ACTION_DELAY_MS 50
#endif // BOOTSLIFETIME_ACTION_DELAY_MS

typedef struct lifetime_data {
	uint32_t boots;
	uint32_t lifetime;
} lifetime_data_t;

#endif // BOOTSLIFETIME_H_
